JSDK-2953 - Video Track TS Definitions
twilio/twilio-video.js pull request #1212
Opened 2020-09-30 22:41 UTC by PikaJoyce

This is a PR for the video track TS definitions.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

2020-10-05 18:11 UTC, mhuynh5757 commented on .gitignore
> +tsdef/twilio-video-tests.js
This shouldn't be necessary if the JS isn't emitted by using `--noEmit` with `tsc`.

2020-10-05 18:16 UTC, mhuynh5757 commented on tsdef/LocalVideoTrack.d.ts
> +  on(event: 'dimensionsChanged', listener: (track: VideoTrack) => void): this;
Event listeners should be able to return `any`, not just `void`.

2020-10-05 21:46 UTC, manjeshbhargav requested changes

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/VideoTrack.d.ts
> +  isEnabled: boolean;
@PikaJoyce This should be in `Track.d.ts`.
```suggestion
```

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/LocalVideoTrack.d.ts
> +  on(event: 'dimensionsChanged', listener: (track: VideoTrack) => any): this;
@PikaJoyce Please change return type of all event listeners to `void` (even the ones already committed).
```suggestion
  on(event: 'dimensionsChanged', listener: (track: VideoTrack) => void): this;
```

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/RemoteVideoTrack.d.ts
> +  priority: Track.Priority;
@PikaJoyce 
```suggestion
  priority: Track.Priority | null;
```

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/RemoteVideoTrack.d.ts
> +  setPriority(priority: Track.Priority): RemoteVideoTrack;
@PikaJoyce 
```suggestion
  setPriority(priority: Track.Priority | null): this;
```

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/VideoTrack.d.ts
> +  _attachments?: HTMLMediaElement[];
@PikaJoyce Please do not add types for private members/methods.
```suggestion
```

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/VideoTrack.d.ts
> +  detach(element?: HTMLMediaElement | string): HTMLMediaElement[];
@PikaJoyce 
```suggestion
  detach(element?: HTMLMediaElement | string): HTMLVideoElement[];
```

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/LocalVideoTrack.d.ts
> +  disable(): LocalVideoTrack;
@PikaJoyce 
```suggestion
  disable(): this;
```

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/LocalVideoTrack.d.ts
> +  enable(enabled?: boolean): LocalVideoTrack;
@PikaJoyce 
```suggestion
  enable(enabled?: boolean): this;
```

2020-10-05 21:46 UTC, manjeshbhargav commented on tsdef/LocalVideoTrack.d.ts
> +  stop(): LocalVideoTrack;
@PikaJoyce 
```suggestion
  stop(): this;
```

2020-10-06 03:18 UTC, manjeshbhargav approved these changes

2020-10-06 03:18 UTC, manjeshbhargav commented on tsdef/RemoteVideoTrack.d.ts
> +  setPriority(priority: Track.Priority): this;
@PikaJoyce 
```suggestion
  setPriority(priority: Track.Priority | null): this;
```

2020-10-06 03:18 UTC, manjeshbhargav commented on tsdef/VideoTrack.d.ts
> +      height: number | null;
@PikaJoyce Nitpick:
```suggestion
    width: number | null;
    height: number | null;
```

2020-10-06 15:22 UTC, merged