JSDK-3003 - stop track before restart
twilio/twilio-video.js pull request #1253
Opened 2020-10-26 19:52 UTC by makarandp0

On some android devices track.restart did not work. This was reported on [this github issue](https://github.com/twilio/twilio-video.js/issues/1180) 

The solution is to stop the current track before restarting using different constraints. 
 

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2020-10-26 23:54 UTC, manjeshbhargav requested changes
@makarandp0 Two requests:
* Please remove code to stop the track before restart for Firefox in `LocalAudioTrack.restart()`.
* Please make sure our unit and integration tests check that the "stopped" event is fired first.

2020-10-30 15:22 UTC, makarandp0 commented
Hey @manjeshbhargav I have incorporated your feedback, Can you take another look?

2020-11-02 16:39 UTC, manjeshbhargav approved these changes

2020-11-02 16:39 UTC, manjeshbhargav commented on CHANGELOG.md
> +  with `Failed to re-acquire MediaStreamTrack`. (JSDK-3003)
```suggestion
- Fixed a bug where restarting a LocalAudioTrack or LocalVideoTrack failed on some android devices. (JSDK-3003)
```

2020-11-02 18:52 UTC, merged