add tests for recording events + update browserify to resolve dependency issue.
twilio/twilio-video.js pull request #1258
Opened 2020-10-30 21:04 UTC by makarandp0

This change adds integration tests to verify recording events.

It also updates browserify to fix test error `RangeError: offset is out of bounds at Uint8Array.set`  when creating tokens. This error is caused by usage of buffer@5.7.0 which introduced a bug in `Buffer.concat` implementation. 
Browserify@14.x used buffer@5.7.0. 
This change moves it to browserify@16.5.2 which uses older version ( buffer@5.2.1 )
 
**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2020-11-02 16:33 UTC, manjeshbhargav approved these changes

2020-11-02 16:33 UTC, manjeshbhargav commented on test/integration/spec/room.js
> +      [true, false].forEach(recordingEnabledAtCreate => {
Use `combinationContext()`.

2020-11-02 16:33 UTC, manjeshbhargav commented on test/integration/spec/room.js
> +                assert.strictEqual(room.isRecording, true);
Please make boolean property verification part of a separate `it()`.

2020-11-02 16:33 UTC, manjeshbhargav commented on test/integration/spec/room.js
> +            localTrack = await waitFor(createLocalVideoTrack(), 'alice local video track');
Please publish 2 tracks and verify `recordingStarted` and `recordingStopped` are fired only once each.

2020-11-06 01:59 UTC, manjeshbhargav requested changes
Please set the base branch to `develop`.

2020-11-06 17:29 UTC, makarandp0 commented
@manjeshbhargav I have updated the PR to be against `develop` now.

2020-11-06 17:49 UTC, manjeshbhargav approved these changes

2020-11-06 17:50 UTC, merged