add connect insight event
twilio/twilio-video.js pull request #1270
Opened 2020-11-12 00:57 UTC by makarandp0

was [previously](https://github.com/twilio/twilio-video.js/pull/1268) 

send room/connect event to insights following schema specified here:
https://code.hq.twilio.com/client/rtc-insights-spec/blob/connect_again/schema/video/event/room/connect.json

with this the logged room/connect event looks like:
https://kibana.dev-us1.eak.twilio.com/video/goto/5c1027ea43adbecc45f03fb94b350ab3

burndown :
- [x] merge https://code.hq.twilio.com/client/rtc-insights-spec/pull/69
- [x] release rtc-insights-spec 1.0.3 
- [ ] re-deploy sdk-ws-gateway 
- [ ] verify
- [ ] merge this PR

- [ ] I acknowledge that all my contributions will be made under the project's license.

2020-11-13 21:02 UTC, makarandp0 commented
@manjeshbhargav - I have incorporated your feedback from https://github.com/twilio/twilio-video.js/pull/1268 in this PR. Please take another look

2020-11-13 21:13 UTC, manjeshbhargav requested changes
@makarandp0 Implementation looks good. However, since there is a new event on the EventObserver, please document it and add a CHANGELOG.md entry.

2020-11-13 21:13 UTC, manjeshbhargav commented on lib/util/index.js
> +      if (typeof connectOptions.bandwidthProfile[prop] === 'number' || typeof connectOptions.bandwidthProfile[prop] === 'string') {
@makarandp0 At this point we would have already validated the bandwidth profile options object. So you just need to check the presence of the property.
```suggestion
      if (prop in connectOptions.bandwidthProfile) {
```

2020-11-13 21:13 UTC, manjeshbhargav commented on lib/util/index.js
> +    if (typeof connectOptions[prop] !== 'undefined') {
```suggestion
    if (prop in connectOptions) {
```

2020-11-13 21:13 UTC, manjeshbhargav commented on lib/util/index.js
> +    if (connectOptions.bandwidthProfile.renderDimensions) {
```suggestion
    if ('renderDimensions' in connectOptions.bandwidthProfile) {
```

2020-11-17 02:24 UTC, manjeshbhargav approved these changes

2020-11-23 18:27 UTC, merged