Msp refactor
twilio/twilio-video.js pull request #1389
Opened 2021-02-18 17:30 UTC by makarandp0

We have lot of boilerplate code to handle MSP channels with VMS failovers, This change refactors it to remove boilerplate. 
This was previously opened as: https://github.com/twilio/twilio-video.js/pull/1386
**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2021-02-18 20:17 UTC, makarandp0 commented
Note: the failing test is caused by [some SFU change](https://twilio.slack.com/archives/C7J8VNN3W/p1613679305089800?thread_ts=1613676373.088600&cid=C7J8VNN3W) in stage:

2021-02-19 18:12 UTC, manjeshbhargav requested changes
@makarandp0 Getting better! However, I have a suggestion. Right now, we seem to have two types of classes: `MediaSignaling` (formerly `MSPTransportHandler`) classes for each MSP channel and the different media signaling classes: `DominantSpeakerSignaling`, `TrackSwitchOffSignaling`, etc. I think it makes sense for each of these media signaling classes to derive from `MediaSignaling`. For ex:

```js
class DominantSpeakerSignaling extends MediaSignaling {
  ...
}
```
Now, instead of having 2 objects `_dominantSpeakerMSP` and `dominantSpeakerSignaling`, we can have only one object `dominantSpeakerSignaling`. We can now listen to both "ready" and "updated" events on the same object.

2021-02-19 18:12 UTC, manjeshbhargav commented on lib/signaling/v2/msptransporthandler.js
> +  isReady() {
Also, `isReady()` is not used anywhere, so you can remove it.

2021-02-19 18:45 UTC, makarandp0 commented
Thanks @manjeshbhargav. I like your suggestion of collapsing MSP Transport with MSP Signaling, however I am afraid that would be a larger change than I wanted to take up - especially on the unit test side - we have lot of unit tests for this signaling classes and such change would invalidate them.

How about we postpone extended refactor for some other day. With the current refactor we have already reduces the code significantly, and made it easy to add new MSP as shown by https://github.com/twilio/twilio-video.js/pull/1391/files

2021-02-22 20:23 UTC, manjeshbhargav reviewed
@makarandp0 Getting better. I have a couple of questions:
1. Why was `updateSubscriberTrackPriority` and `setTrackPrioritySignaling` removed from `lib/signaling/participant.js`?
2. I see that there were mostly removal of unit tests and not new tests for the refactored code. Are you planning to add it in another commit?

2021-02-22 20:23 UTC, manjeshbhargav commented on lib/signaling/v2/dominantspeakersignaling.js
> +    this.on('ready', mediaSignalingTransport => {
Nitpick:
```suggestion
    this.on('ready', transport => {
```

2021-02-22 20:23 UTC, manjeshbhargav commented on lib/signaling/v2/networkqualitysignaling.js
> +    this.on('ready', mediaSignalingTransport => {
Nitpick:
```suggestion
    this.on('ready', transport => {
```

2021-02-22 20:23 UTC, manjeshbhargav commented on lib/signaling/v2/trackprioritysignaling.js
> +    this.on('ready', mediaSignalingTransport => {
NitpicK:
```suggestion
    this.on('ready', transport => {
```

2021-02-22 20:23 UTC, manjeshbhargav commented on lib/signaling/v2/trackswitchoffsignaling.js
> +    this.on('ready', mediaSignalingTransport => {
Nitpick:
```suggestion
    this.on('ready', transport => {
```

2021-02-22 20:23 UTC, manjeshbhargav commented on test/unit/spec/signaling/v2/room.js
> +            // });
```suggestion
```

2021-02-22 20:23 UTC, manjeshbhargav commented on test/unit/spec/signaling/v2/room.js
> +        // });
```suggestion
```

2021-02-22 20:23 UTC, manjeshbhargav commented on test/unit/spec/signaling/v2/room.js
> +          // });
```suggestion
```

2021-02-22 22:19 UTC, makarandp0 commented
Thanks @manjeshbhargav for taking a look I have incorporated your suggestions now.
> Why was updateSubscriberTrackPriority and setTrackPrioritySignaling removed from lib/signaling/participant.js?

`updateSubscriberTrackPriority` is moved to lib/signaling/v2/remoteparticipant.js because it's only applicable to RemoteParticipants. About `Participant!setTrackPrioritySignaling` - it was needed previously before because MSP signaling objects could get destroyed, and recreated for VMS failovers, With this refactor we are keeping Signaling class objects for the lifetime of room object, and just recreate transport objects inside those signaling objects. So  `Participant!setTrackPrioritySignaling` is not needed anymore. Any code to cache priorities is now moved to trackprioritysignaling.js

> I see that there were mostly removal of unit tests and not new tests for the refactored code. Are you planning to add it in another commit?

tests were removed because they are not applicable anymore (because room does not recreate signaling objects on VMS failovers). I see that we have same code coverage after refactored code  
https://38102-46595751-gh.circle-artifacts.com/0/coverage/lcov-report/lib/signaling/v2/mediasignaling.js.html
https://38102-46595751-gh.circle-artifacts.com/0/coverage/lcov-report/lib/signaling/v2/dominantspeakersignaling.js.html
https://38102-46595751-gh.circle-artifacts.com/0/coverage/lcov-report/lib/signaling/v2/networkqualitysignaling.js.html
But I noticed missing coverage for two branches and have added additional tests to validate refactored code in trackprioritysignaling.js

2021-02-23 04:53 UTC, makarandp0 commented
@manjeshbhargav, I have now added tests for `mediasignaling.js` - Please take another look

2021-02-23 21:46 UTC, manjeshbhargav approved these changes

2021-02-23 21:51 UTC, merged