VIDEO-7161 + VIDEO-7162 Simulcast API implementation + rollback support
twilio/twilio-video.js pull request #1591
Opened 2021-10-04 18:36 UTC by makarandp0

This change implements the proposed API for adaptive simulcast.

Now we `connect` will accept a value of 'auto' for preferredVideoCodecs. This new values would enable adaptive simulcast. Meaning we will enable simulcast and ask for 'publisher_hints' msp channel in initial connect message.

To handle the case for P2P room (where we do not want to enable simulcast) SDK will check for availability of publisher_hints msp in `connected` message, and if not available then rollback the offer that was sent with simulcast enabled.

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

2021-10-05 00:03 UTC, manjeshbhargav requested changes

2021-10-05 18:14 UTC, makarandp0 commented on lib/connect.js
> +    options.preferredVideoCodecs = [{ codec: 'VP8', simulcast: true, adaptiveSimulcast: true }];
Good point, so far its decided to that this not part of public API.  we could maintain this settings separately but it really belongs here, Once we move to typescript  we could cast this type as 
```
export interface VP8CodecSettings extends VideoCodecSettings {
  codec: 'VP8';
  simulcast?: boolean;
}

export interface InternalVP8CodecSettings extends VP8CodecSettings {
  adaptiveSimulcast?: boolean;
}

```

2021-10-05 18:42 UTC, makarandp0 commented on lib/signaling/v2/peerconnection.js
> +  setEffectiveAdaptiveSimulcast(effectiveAdaptiveSimulcast) {
This is called from Room, not sure making it '_' gives wrong impression that its private/protected.

2021-10-06 18:07 UTC, manjeshbhargav approved these changes
LGTM. However, please create a ticket to add a CHANGELOG.md entry for this feature.

2021-10-06 18:37 UTC, merged

2021-10-07 07:42 UTC, KaelWD commented
Does this resolve #1398? We want to disable simulcast in group rooms with only two participants as well, not just P2P rooms.