Merge from master
twilio/twilio-video.js pull request #1843
Opened 2022-08-01 21:05 UTC by makarandp0

This change merges from master, so that large room can use krisp noise cancelation beta.
**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### Description

A description of what this PR does.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

2022-08-02 20:06 UTC, manjeshbhargav requested changes

2022-08-02 20:06 UTC, manjeshbhargav commented on CHANGELOG.md
> -
Please add the new line back.

2022-08-02 20:06 UTC, manjeshbhargav commented on CHANGELOG.md
> +======================
Please add a new line here.
```suggestion
======================

```

2022-08-02 20:06 UTC, manjeshbhargav commented on CHANGELOG.md
> +
Remove extra line here.
```suggestion
```

2022-08-02 20:06 UTC, manjeshbhargav commented on CHANGELOG.md
> +```
Add extra line here.

2022-08-09 17:59 UTC, makarandp0 commented
Thank you for feedback @manjeshbhargav Please take another look

2022-08-09 18:35 UTC, manjeshbhargav approved these changes
@makarandp0 LGTM. However, can you create a `feature/large-rooms-with-krisp` branch from the `feature/large-rooms-pilot` branch, and merge your changes to it? I'm asking because the next preview release will only have the fix to `getStats()`, and I need the main feature branch clean.

2022-09-29 20:17 UTC, closed without merging