getStats es6 syntax
twilio/twilio-video.js pull request #1937
Opened 2022-11-28 19:29 UTC by schayapathi

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### Description

Declaring default values in function declaration, object/array destructuring, concise require statements

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [x] Ready for review

2022-11-29 20:08 UTC, PikaJoyce requested changes

2022-11-29 20:08 UTC, PikaJoyce commented on lib/webrtc/getstats.js
> +  const standardizedLocalCandidateStatsKeys = standardizedCandidateStatsKeys.concat([
We can use the spread operator here instead of concat.

2022-11-29 20:08 UTC, PikaJoyce commented on lib/webrtc/getstats.js
> +  const standardizedLocalCandidateStatsKeys = standardizedCandidateStatsKeys.concat([
We can use the spread operator here instead of concat.

2022-12-06 00:45 UTC, manjeshbhargav approved these changes

2022-12-06 00:45 UTC, manjeshbhargav commented on lib/webrtc/getstats.js
> +    const isRemote = triple[2];
```suggestion
  ], ([tracks, statsArrayName, isRemote]) => {
```

2022-12-06 00:45 UTC, manjeshbhargav commented on lib/webrtc/getstats.js
> +    const getStatValue = name => {
Revert to function.

2022-12-06 20:18 UTC, merged