VIDEO-11360 LocalMediaTrack.isMuted and Room.refreshInactiveMedia.
twilio/twilio-video.js pull request #1944
Opened 2022-12-02 20:31 UTC by manjeshbhargav

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### Description

This PR implements the following [proposal](https://docs.google.com/document/d/1hVDcsMLAAEL2uuES5Dzl6KXRtnqMDt-5hxZBd8u9kW0/edit?usp=sharing) for working around [VIDEO-11360](https://issues.corp.twilio.com/browse/VIDEO-11360).

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [x] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

2022-12-02 23:32 UTC, PikaJoyce requested changes
Awesome work Manjesh!!! Left a couple of comments/questions mostly. Otherwise, implementation looks great!

2022-12-02 23:32 UTC, PikaJoyce commented on lib/media/track/localaudiotrack.js
> -   * Disable the {@link LocalAudioTrack}. This is effectively "mute".
I think if we remove `This is effectively "mute"`, perhaps we need to be more clear about what the differences are between mute/unmute and disable/enable are.

Perhaps adding 
```This is effectively "pause"```

2022-12-02 23:32 UTC, PikaJoyce commented on lib/media/track/localaudiotrack.js
> -   * Enable the {@link LocalAudioTrack}. This is effectively "unmute".
Same as above comment.

Perhaps adding
`This is effectively "play"`

2022-12-02 23:32 UTC, PikaJoyce commented on lib/media/track/localaudiotrack.js
> - * The {@link LocalAudioTrack} was disabled, i.e. "muted".
Same as above comments about renaming "muted" to "paused" and "unmuted" to "play".

2022-12-02 23:32 UTC, PikaJoyce commented on lib/media/track/localaudiotrack.js
> - * The {@link LocalAudioTrack} was enabled, i.e. "unmuted".
Same as above comment

2022-12-03 00:15 UTC, manjeshbhargav commented on lib/media/track/localaudiotrack.js
> + *   events are fired appropriately
Typically we don't use periods for describing properties or methods.

2022-12-05 21:53 UTC, PikaJoyce approved these changes
LGTM!

2022-12-06 00:03 UTC, merged